import { useState, useEffect } from 'react';
import Head from 'next/head';

import Navbar from '../components/Navbar';
import ImageCarousel from '../components/ImageCarousel';
import axios from 'axios';

interface Props{
  slides: any
}

export async function getStaticProps(){
  let data: any;
  try{
    const response = await axios.get('http://localhost:3000/api/home/slides');
    data = await response.data.data;
  }catch(err: any){
    console.log(err);
  }
  return {
    props: {
      slides: data
    }
  }
}

export default function Home(props: Props) {
  useState(()=>{
    console.log(props.slides)
  });

  return (
    <div className='index'>
      <Head>
        <title>Pokémart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ballLogo.png" />
      </Head>
      <Navbar />
      <ImageCarousel
        slides={props.slides}
      />
    </div>
  )
}
